"""add association table

Revision ID: 8cadf2b74f0b
Revises: cfd6c1c8c1ef
Create Date: 2023-10-20 00:35:44.114303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cadf2b74f0b'
down_revision = 'cfd6c1c8c1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rental_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rental_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], name=op.f('fk_user_rental_association_rental_id_rentals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_rental_association_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rental_association')
    # ### end Alembic commands ###
